global:
  scrape_interval: 5s

scrape_configs:
  - job_name: account-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["account-service:8081"]
  - job_name: settlement-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["settlement-service:8082"]
  - job_name: ledger-query-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ledger-query-service:8083"]
  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8084"]
